apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "basic.names.fullname" . }}
  namespace: {{ include "basic.names.fullname.namespace" . | quote }}
rules:
  - apiGroups: [ "*" ]
    resources: [ "*" ]
    verbs: [ "*" ]
