apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: {{ include "basic.names.fullname" . }}
  namespace: {{ include "basic.names.fullname.namespace" . | quote }}
  annotations:
    kubernetes.io/service-account.name: {{ include "basic.names.fullname" . }}