apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: {{ .Chart.Name | quote }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    kubernetes.io/service-account.name: {{ .Chart.Name | quote }}