apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "basic.names.fullname" . }}
  namespace: {{ include "basic.names.fullname.namespace" . | quote }}
data:
  AWS_REGION: {{ .Values.aws.region | quote }}
  DOCKER_SECRET_NAME: {{ .Values.secretName | quote }}