apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name | quote }}
  namespace: {{ .Release.Namespace | quote }}
data:
  AWS_REGION: {{ .Values.aws.region | quote }}
  DOCKER_SECRET_NAME: {{ .Values.secretName | quote }}