apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Chart.Name | quote }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  schedule: {{ .Values.cronJobSchedule | quote }}
  successfulJobsHistoryLimit: {{ .Values.successfulJobsHistoryLimit | int }}
  failedJobsHistoryLimit: {{ .Values.failedJobsHistoryLimit | int }}
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ .Chart.Name | quote }}
          containers:
            - name: {{ .Chart.Name | quote }}
              image: {{ include "erc-registry-helpers.image" . }}
              envFrom:
                - secretRef:
                    name: {{ .Chart.Name | quote }}
                - configMapRef:
                    name: {{ .Chart.Name | quote }}
              imagePullPolicy: Always
          restartPolicy: Never