apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "basic.names.fullname" . }}
  namespace: {{ include "basic.names.fullname.namespace" .  | quote }}
spec:
  schedule: {{ .Values.cronJobSchedule | quote }}
  successfulJobsHistoryLimit: {{ .Values.successfulJobsHistoryLimit | int }}
  failedJobsHistoryLimit: {{ .Values.failedJobsHistoryLimit | int }}
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ include "basic.names.fullname" . }}
          containers:
            - name: {{ include "basic.names.fullname" . }}
              image: {{ include "basic.images.image" . }}
              env:
                - name: NAMESPACE_NAME
                  value: {{ include "basic.names.fullname.namespace" . | quote }}
              envFrom:
                - secretRef:
                    name: {{ include "basic.names.fullname" . }}
                - configMapRef:
                    name: {{ include "basic.names.fullname" . }}
              imagePullPolicy: Always
          restartPolicy: Never