apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "basic.names.fullname" . }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  namespace: {{ include "basic.names.fullname.namespace" . | quote }}
spec:
  template:
    spec:
      serviceAccountName: {{ include "basic.names.fullname" . }}
      containers:
        - name: {{ include "basic.names.fullname" . }}
          image: {{ include "basic.images.image" . }}
          env:
            - name: NAMESPACE_NAME
              value: {{ include "basic.names.fullname.namespace" . | quote }}
          envFrom:
            - secretRef:
                name: {{ include "basic.names.fullname" . }}
            - configMapRef:
                name: {{ include "basic.names.fullname" . }}
          imagePullPolicy: Always
      restartPolicy: Never