apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name | quote }}
  namespace: {{ .Release.Namespace | quote }}
rules:
  - apiGroups: [ "" ]
    resources:
      - secrets
    resourceNames:
      - {{ .Values.secretName | quote }}
    verbs:
      - delete
      - create
