kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name | quote }}
  namespace: {{ .Release.Namespace | quote }}

subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name | quote }}
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: {{ .Release.Name| quote }}
  apiGroup: rbac.authorization.k8s.io
