kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "basic.names.fullname" . }}
  namespace: {{ include "basic.names.fullname.namespace" . | quote }}

subjects:
  - kind: ServiceAccount
    name: {{ include "basic.names.fullname" . }}
roleRef:
  kind: Role
  name: {{ include "basic.names.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
