apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name | quote }}
  namespace: {{ .Release.Namespace | quote }}
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.aws.accessKeyID | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.aws.secretAccessKey | quote }}
  AWS_ACCOUNT: {{ .Values.aws.account | quote }}