name: Create Helm Chart

on:
  push:
    branches: [ prod ]
  workflow_dispatch:

permissions:
  contents: write
  actions: write

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}-create-helm-chart"
  cancel-in-progress: true

jobs:
  vars:
    name: Generation vars
    runs-on: ubuntu-latest
    outputs:
      branch_pages: ${{ steps.dynamic.outputs.branch_pages }}
    steps:
      - uses: actions/checkout@v4

      - name: Create dynamic vars
        id: dynamic
        run: |
          echo "branch_pages=pages" >> "$GITHUB_OUTPUT"

  run_test:
    needs: [ vars ]
    name: Run workflow - test
    uses: ./.github/workflows/test.yaml
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-run_manual
      cancel-in-progress: true

  deploy_to_pages:
    needs: [ vars, run_test ]
    name: Deploy helm charts to github pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: charts
          pages_branch: ${{ needs.vars.outputs.branch_pages }}
        env:
          CR_TOKEN: ${{ github.token }}

      - name: Run workflow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # need use this bad use for manual run workflow in specific branch 
          gh workflow run deploy-pages.yaml --ref ${{ needs.vars.outputs.branch_pages }}