name: Test Helm Chart

on:
  push:
    branches: [ dev ]
  workflow_dispatch:
  workflow_call:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}-${{ github.event.workflow_call.workflow_file }}"
  cancel-in-progress: true

jobs:
  vars:
    name: Generation vars
    runs-on: ubuntu-latest
    outputs:
      path_to_charts: ${{ steps.dynamic.outputs.PATH_TO_CHARS }}
    steps:
      - uses: actions/checkout@v4
      - name: Check all charts
        working-directory: charts
        id: _tmp_path_to_charts
        run: |
          echo "value=$( echo $(find . -maxdepth 1 -mindepth 1 -type d -exec realpath {} \;) }} )" >> "$GITHUB_OUTPUT"
      - name: Create dynamic vars
        id: dynamic
        run: |
          echo "PATH_TO_CHARS=${{ steps._tmp_path_to_charts.outputs.value }}" >> "$GITHUB_OUTPUT"

  lint-best-practices:
    needs: [ vars ]
    name: Short check is valid schema # Поверхнева перевірка template. Не перевіряє, чи валідні template в k8s
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint - Best practices
        working-directory: charts
        run: helm lint *

  lint-helm:
    needs: [ vars ]
    name: Check valid schema in k8s # поглинена перевірка template, чи відповідають стандарту k8s
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path: ${{ needs.vars.output.path_to_charts }}

    steps:
      - uses: actions/checkout@v4
      - name: Install plugin
        run: |
          helm plugin install https://github.com/jtyr/kubeconform-helm
      - name: Check valid helm
        working-directory: ${{ matrix.path }}
        run: |
          helm kubeconform --verbose --summary .

